### ISSUE TITLE
读取风云2G卫星资料时出错

### ISSUE THREAD

**Issue by ZhiboGao** [wqshen/AwxReader#5]
您好，我最近成功安装了awx库，但是发现，读取2G资料的时候，报错，错误如下：

输入命令：
awx_info Z_SATE_C_BAWX_20200810073014_P_FY2G_TBB_IR1_OTG_20200810_0600.AWX

报错结果
Traceback (most recent call last):
  File "/home/bozhero/miniconda3/envs/weixing/bin/awx_info", line 8, in <module>
    sys.exit(_info())
             ^^^^^^^
  File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 358, in _info
    awx = Awx(args.filename)
          ^^^^^^^^^^^^^^^^^^
  File "<string>", line 14, in __init__
  File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 111, in __post_init__
    self.read(self.pathfile)
  File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 173, in read
    self._deconstruct_filename(path_or_bytes)
  File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 328, in _deconstruct_filename
    self.name = AwxFileName(*os.path.splitext(os.path.basename(filename))[0].split('_'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AwxFileName.__init__() takes 7 positional arguments but 13 were given

请教博主，该如何解决此问题，谢谢

**Comment by wqshen** [comment]
> 您好，我最近成功安装了awx库，但是发现，读取2G资料的时候，报错，错误如下：
> 
> 输入命令：
> awx_info Z_SATE_C_BAWX_20200810073014_P_FY2G_TBB_IR1_OTG_20200810_0600.AWX
> 
> 报错结果
> Traceback (most recent call last):
>   File "/home/bozhero/miniconda3/envs/weixing/bin/awx_info", line 8, in <module>
>     sys.exit(_info())
>              ^^^^^^^
>   File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 358, in _info
>     awx = Awx(args.filename)
>           ^^^^^^^^^^^^^^^^^^
>   File "<string>", line 14, in __init__
>   File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 111, in __post_init__
>     self.read(self.pathfile)
>   File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 173, in read
>     self._deconstruct_filename(path_or_bytes)
>   File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/__init__.py", line 328, in _deconstruct_filename
>     self.name = AwxFileName(*os.path.splitext(os.path.basename(filename))[0].split('_'))
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: AwxFileName.__init__() takes 7 positional arguments but 13 were given
> 
> 请教博主，该如何解决此问题，谢谢

这个报错写的很明确了，咋们这个文件的文件名与卫星中心网站的上是不一样的，看起来是下发的文件，awx代码里会通过解析文件名获取一些信息，在这个过程中出现了问题。
解决办法，一是我这边可以修改awx库，尽量规避这一问题；另外你也可以重命名文件临时解决问题。

**Comment by ZhiboGao** [comment]
谢谢老师及时回复，修改后可以了，学到很多，很实用的一个库，非常感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wqshen/AwxReader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wqshen/AwxReader] 读取风云2G卫星资料时出错 (Issue #5)





  
您好，我最近成功安装了awx库，但是发现，读取2G资料的时候，报错，错误如下：
 
输入命令：
 awx_info Z_SATE_C_BAWX_20200810073014_P_FY2G_TBB_IR1_OTG_20200810_0600.AWX
 
报错结果
 Traceback (most recent call last):
 File "/home/bozhero/miniconda3/envs/weixing/bin/awx_info", line 8, in 
 sys.exit(_info())
 ^^^^^^^
 File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 358, in _info
 awx = Awx(args.filename)
 ^^^^^^^^^^^^^^^^^^
 File "", line 14, in init
 File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 111, in post_init
 self.read(self.pathfile)
 File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 173, in read
 self._deconstruct_filename(path_or_bytes)
 File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 328, in deconstruct_filename
 self.name = AwxFileName(*os.path.splitext(os.path.basename(filename))[0].split(''))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: AwxFileName.init() takes 7 positional arguments but 13 were given
 
请教博主，该如何解决此问题，谢谢
  
这个报错写的很明确了，咋们这个文件的变量名与卫星中心网站的上是不一样的，看起来是下发的文件，awx代码里会通过解析变量名获取一些信息，在这个过程中出现了问题。
 解决办法，一是我这边可以修改awx库，尽量规避这一问题；另外你也可以重命名文件临时解决问题。

**Comment by wqshen** [comment]
> 谢谢老师及时回复，修改后可以了，学到很多，很实用的一个库，非常感谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wqshen/AwxReader" ***@***.***&gt;; 发送时间:&nbsp;2024年7月24日(星期三) 下午4:58 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wqshen/AwxReader] 读取风云2G卫星资料时出错 (Issue #5) 您好，我最近成功安装了awx库，但是发现，读取2G资料的时候，报错，错误如下： 输入命令： awx_info Z_SATE_C_BAWX_20200810073014_P_FY2G_TBB_IR1_OTG_20200810_0600.AWX 报错结果 Traceback (most recent call last): File "/home/bozhero/miniconda3/envs/weixing/bin/awx_info", line 8, in sys.exit(_info()) ^^^^^^^ File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 358, in _info awx = Awx(args.filename) ^^^^^^^^^^^^^^^^^^ File "", line 14, in init File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 111, in post_init self.read(self.pathfile) File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 173, in read self._deconstruct_filename(path_or_bytes) File "/home/bozhero/miniconda3/envs/weixing/lib/python3.12/site-packages/awx/init.py", line 328, in deconstruct_filename self.name = AwxFileName(*os.path.splitext(os.path.basename(filename))[0].split('')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: AwxFileName.init() takes 7 positional arguments but 13 were given 请教博主，该如何解决此问题，谢谢 这个报错写的很明确了，咋们这个文件的变量名与卫星中心网站的上是不一样的，看起来是下发的文件，awx代码里会通过解析变量名获取一些信息，在这个过程中出现了问题。 解决办法，一是我这边可以修改awx库，尽量规避这一问题；另外你也可以重命名文件临时解决问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

已经更新代码，现在可以直接读取了，你可以clone下来安装使用，pypi上的包我过段时间再更新
